In [3]:
import pandas as pd
import numpy as np
import requests
import json
# from 4/4/22 0:00 UTC to 5/23/22 0:00 UTC 
pd.set_option("display.precision", 15)
#df.index.name='Index1' = to give index a name 
#/markets/GMT-PERP/candles?resolution={resolution}&start_time={start_time}&end_time={end_time}
market = requests.get('https://ftx.com/api/markets/ALGO-PERP/candles?resolution=86400&start_time=1649116800&end_time=1653264000').json()
df = pd.DataFrame(market['result'])

some_variable = df.loc[0:50]
print(some_variable)
df

                    startTime             time    open    high     low  \
0   2022-04-05T00:00:00+00:00  1649116800000.0  0.8828  0.9009  0.8283
1   2022-04-06T00:00:00+00:00  1649203200000.0  0.8348  0.8378  0.7643
2   2022-04-07T00:00:00+00:00  1649289600000.0  0.7659  0.8079  0.7501
3   2022-04-08T00:00:00+00:00  1649376000000.0  0.7990  0.8095  0.7512
4   2022-04-09T00:00:00+00:00  1649462400000.0  0.7589  0.7898  0.7573
5   2022-04-10T00:00:00+00:00  1649548800000.0  0.7880  0.7902  0.7466
6   2022-04-11T00:00:00+00:00  1649635200000.0  0.7503  0.7609  0.6812
7   2022-04-12T00:00:00+00:00  1649721600000.0  0.6932  0.7447  0.6855
8   2022-04-13T00:00:00+00:00  1649808000000.0  0.7254  0.7478  0.7134
9   2022-04-14T00:00:00+00:00  1649894400000.0  0.7462  0.7612  0.7147
10  2022-04-15T00:00:00+00:00  1649980800000.0  0.7265  0.7433  0.7211
11  2022-04-16T00:00:00+00:00  1650067200000.0  0.7396  0.7515  0.7280
12  2022-04-17T00:00:00+00:00  1650153600000.0  0.7437  0.7456  0.7059
13  2022-04-18T00:00:00+00:00  1650240000000.0  0.7101  0.7406  0.6874
14  2022-04-19T00:00:00+00:00  1650326400000.0  0.7369  0.7635  0.7286
15  2022-04-20T00:00:00+00:00  1650412800000.0  0.7595  0.7717  0.7300
16  2022-04-21T00:00:00+00:00  1650499200000.0  0.7418  0.7745  0.7068
17  2022-04-22T00:00:00+00:00  1650585600000.0  0.7183  0.7316  0.7112
18  2022-04-23T00:00:00+00:00  1650672000000.0  0.7189  0.7238  0.7035
19  2022-04-24T00:00:00+00:00  1650758400000.0  0.7074  0.7147  0.6966
20  2022-04-25T00:00:00+00:00  1650844800000.0  0.7009  0.7059  0.6555
21  2022-04-26T00:00:00+00:00  1650931200000.0  0.7032  0.7284  0.6422
22  2022-04-27T00:00:00+00:00  1651017600000.0  0.6560  0.6787  0.6485
23  2022-04-28T00:00:00+00:00  1651104000000.0  0.6714  0.7155  0.6611
24  2022-04-29T00:00:00+00:00  1651190400000.0  0.6984  0.7099  0.6185
25  2022-04-30T00:00:00+00:00  1651276800000.0  0.6377  0.6394  0.5375
26  2022-05-01T00:00:00+00:00  1651363200000.0  0.5667  0.6050  0.5636
27  2022-05-02T00:00:00+00:00  1651449600000.0  0.6013  0.6477  0.5795
28  2022-05-03T00:00:00+00:00  1651536000000.0  0.6159  0.7423  0.6109
29  2022-05-04T00:00:00+00:00  1651622400000.0  0.6709  0.7191  0.6529
30  2022-05-05T00:00:00+00:00  1651708800000.0  0.7154  0.7301  0.6133
31  2022-05-06T00:00:00+00:00  1651795200000.0  0.6335  0.7250  0.6259
32  2022-05-07T00:00:00+00:00  1651881600000.0  0.6979  0.7743  0.6720
33  2022-05-08T00:00:00+00:00  1651968000000.0  0.7489  0.7853  0.7069
34  2022-05-09T00:00:00+00:00  1652054400000.0  0.7297  0.7557  0.5660
35  2022-05-10T00:00:00+00:00  1652140800000.0  0.5740  0.6607  0.5520
36  2022-05-11T00:00:00+00:00  1652227200000.0  0.5845  0.6070  0.4024
37  2022-05-12T00:00:00+00:00  1652313600000.0  0.4497  0.4808  0.3410
38  2022-05-13T00:00:00+00:00  1652400000000.0  0.4221  0.5086  0.4142
39  2022-05-14T00:00:00+00:00  1652486400000.0  0.4425  0.4732  0.4176
40  2022-05-15T00:00:00+00:00  1652572800000.0  0.4628  0.4935  0.4434
41  2022-05-16T00:00:00+00:00  1652659200000.0  0.4901  0.4901  0.4369
42  2022-05-17T00:00:00+00:00  1652745600000.0  0.4598  0.5079  0.4585
43  2022-05-18T00:00:00+00:00  1652832000000.0  0.4947  0.5041  0.4305
44  2022-05-19T00:00:00+00:00  1652918400000.0  0.4327  0.4635  0.4202
45  2022-05-20T00:00:00+00:00  1653004800000.0  0.4511  0.4588  0.4191
46  2022-05-21T00:00:00+00:00  1653091200000.0  0.4325  0.4431  0.4206
47  2022-05-22T00:00:00+00:00  1653177600000.0  0.4344  0.4489  0.4230
48  2022-05-23T00:00:00+00:00  1653264000000.0  0.4420  0.4522  0.4096

     close                 volume
0   0.8347  6.978966990400000e+07
1   0.7659  3.649464651460000e+07
2   0.7990  1.887378407620000e+07
3   0.7589  2.081523143410000e+07
4   0.7880  1.311069383560000e+07
5   0.7503  1.095482261310000e+07
6   0.6932  2.726449320250000e+07
7   0.7254  2.243988993640000e+07
8   0.7462  1.802302192320000e+07
9   0.7265  1.134033843010000e+07
10  0.7396  8.565597744000001e+06
11  0.7437  6.606888016300000e+06
12  0.7101  9.420719153899999e+06
13  0.7369  1.857266684490000e+07
14  0.7595  1.617365899580000e+07
15  0.7418  1.103098213640000e+07
16  0.7183  1.697453145510000e+07
17  0.7189  1.041763851980000e+07
18  0.7074  7.972170855000000e+06
19  0.7009  5.818664346500000e+06
20  0.7032  1.901698079520000e+07
21  0.6560  2.759058457030000e+07
22  0.6714  1.285599358450000e+07
23  0.6984  1.869191950600000e+07
24  0.6377  2.321165805060000e+07
25  0.5667  1.189056376310000e+07
26  0.6013  1.715567706040000e+07
27  0.6159  3.837886490970000e+07
28  0.6709  1.934481474205000e+08
29  0.7154  6.522399259840000e+07
30  0.6335  4.186791458060000e+07
31  0.6970  8.092706703470001e+07
32  0.7489  1.168726155899000e+08
33  0.7297  1.263103229016000e+08
34  0.5740  9.942361040850000e+07
35  0.5845  9.052578378070000e+07
36  0.4490  1.156688699542000e+08
37  0.4221  8.015542303370000e+07
38  0.4425  4.556537297160000e+07
39  0.4628  3.157048546790000e+07
40  0.4901  2.195762893510000e+07
41  0.4598  2.702456020490000e+07
42  0.4947  3.646436290950000e+07
43  0.4327  2.808828493320000e+07
44  0.4511  2.699510722250000e+07
45  0.4325  2.358605305730000e+07
46  0.4344  2.331693802100000e+07
47  0.4420  2.201282781480000e+07
48  0.4165  2.259577373480000e+07

,startTime,time,open,high,low,close,volume
0,2022-04-05T00:00:00+00:00,1649116800000.0,0.8828,0.9009,0.8283,0.8347,6.978966990400000e+07
1,2022-04-06T00:00:00+00:00,1649203200000.0,0.8348,0.8378,0.7643,0.7659,3.649464651460000e+07
2,2022-04-07T00:00:00+00:00,1649289600000.0,0.7659,0.8079,0.7501,0.7990,1.887378407620000e+07
3,2022-04-08T00:00:00+00:00,1649376000000.0,0.7990,0.8095,0.7512,0.7589,2.081523143410000e+07
4,2022-04-09T00:00:00+00:00,1649462400000.0,0.7589,0.7898,0.7573,0.7880,1.311069383560000e+07
5,2022-04-10T00:00:00+00:00,1649548800000.0,0.7880,0.7902,0.7466,0.7503,1.095482261310000e+07
6,2022-04-11T00:00:00+00:00,1649635200000.0,0.7503,0.7609,0.6812,0.6932,2.726449320250000e+07
7,2022-04-12T00:00:00+00:00,1649721600000.0,0.6932,0.7447,0.6855,0.7254,2.243988993640000e+07
8,2022-04-13T00:00:00+00:00,1649808000000.0,0.7254,0.7478,0.7134,0.7462,1.802302192320000e+07
9,2022-04-14T00:00:00+00:00,1649894400000.0,0.7462,0.7612,0.7147,0.7265,1.134033843010000e+07
10,2022-04-15T00:00:00+00:00,1649980800000.0,0.7265,0.7433,0.7211,0.7396,8.565597744000001e+06
11,2022-04-16T00:00:00+00:00,1650067200000.0,0.7396,0.7515,0.7280,0.7437,6.606888016300000e+06
12,2022-04-17T00:00:00+00:00,1650153600000.0,0.7437,0.7456,0.7059,0.7101,9.420719153899999e+06
13,2022-04-18T00:00:00+00:00,1650240000000.0,0.7101,0.7406,0.6874,0.7369,1.857266684490000e+07
14,2022-04-19T00:00:00+00:00,1650326400000.0,0.7369,0.7635,0.7286,0.7595,1.617365899580000e+07
15,2022-04-20T00:00:00+00:00,1650412800000.0,0.7595,0.7717,0.7300,0.7418,1.103098213640000e+07
16,2022-04-21T00:00:00+00:00,1650499200000.0,0.7418,0.7745,0.7068,0.7183,1.697453145510000e+07
17,2022-04-22T00:00:00+00:00,1650585600000.0,0.7183,0.7316,0.7112,0.7189,1.041763851980000e+07
18,2022-04-23T00:00:00+00:00,1650672000000.0,0.7189,0.7238,0.7035,0.7074,7.972170855000000e+06
19,2022-04-24T00:00:00+00:00,1650758400000.0,0.7074,0.7147,0.6966,0.7009,5.818664346500000e+06
20,2022-04-25T00:00:00+00:00,1650844800000.0,0.7009,0.7059,0.6555,0.7032,1.901698079520000e+07
21,2022-04-26T00:00:00+00:00,1650931200000.0,0.7032,0.7284,0.6422,0.6560,2.759058457030000e+07
22,2022-04-27T00:00:00+00:00,1651017600000.0,0.6560,0.6787,0.6485,0.6714,1.285599358450000e+07
23,2022-04-28T00:00:00+00:00,1651104000000.0,0.6714,0.7155,0.6611,0.6984,1.869191950600000e+07
24,2022-04-29T00:00:00+00:00,1651190400000.0,0.6984,0.7099,0.6185,0.6377,2.321165805060000e+07
25,2022-04-30T00:00:00+00:00,1651276800000.0,0.6377,0.6394,0.5375,0.5667,1.189056376310000e+07
26,2022-05-01T00:00:00+00:00,1651363200000.0,0.5667,0.6050,0.5636,0.6013,1.715567706040000e+07
27,2022-05-02T00:00:00+00:00,1651449600000.0,0.6013,0.6477,0.5795,0.6159,3.837886490970000e+07
28,2022-05-03T00:00:00+00:00,1651536000000.0,0.6159,0.7423,0.6109,0.6709,1.934481474205000e+08
29,2022-05-04T00:00:00+00:00,1651622400000.0,0.6709,0.7191,0.6529,0.7154,6.522399259840000e+07
30,2022-05-05T00:00:00+00:00,1651708800000.0,0.7154,0.7301,0.6133,0.6335,4.186791458060000e+07
31,2022-05-06T00:00:00+00:00,1651795200000.0,0.6335,0.7250,0.6259,0.6970,8.092706703470001e+07
32,2022-05-07T00:00:00+00:00,1651881600000.0,0.6979,0.7743,0.6720,0.7489,1.168726155899000e+08
33,2022-05-08T00:00:00+00:00,1651968000000.0,0.7489,0.7853,0.7069,0.7297,1.263103229016000e+08
34,2022-05-09T00:00:00+00:00,1652054400000.0,0.7297,0.7557,0.5660,0.5740,9.942361040850000e+07
35,2022-05-10T00:00:00+00:00,1652140800000.0,0.5740,0.6607,0.5520,0.5845,9.052578378070000e+07
36,2022-05-11T00:00:00+00:00,1652227200000.0,0.5845,0.6070,0.4024,0.4490,1.156688699542000e+08
37,2022-05-12T00:00:00+00:00,1652313600000.0,0.4497,0.4808,0.3410,0.4221,8.015542303370000e+07
38,2022-05-13T00:00:00+00:00,1652400000000.0,0.4221,0.5086,0.4142,0.4425,4.556537297160000e+07
39,2022-05-14T00:00:00+00:00,1652486400000.0,0.4425,0.4732,0.4176,0.4628,3.157048546790000e+07
40,2022-05-15T00:00:00+00:00,1652572800000.0,0.4628,0.4935,0.4434,0.4901,2.195762893510000e+07
41,2022-05-16T00:00:00+00:00,1652659200000.0,0.4901,0.4901,0.4369,0.4598,2.702456020490000e+07
42,2022-05-17T00:00:00+00:00,1652745600000.0,0.4598,0.5079,0.4585,0.4947,3.646436290950000e+07
43,2022-05-18T00:00:00+00:00,1652832000000.0,0.4947,0.5041,0.4305,0.4327,2.808828493320000e+07
44,2022-05-19T00:00:00+00:00,1652918400000.0,0.4327,0.4635,0.4202,0.4511,2.699510722250000e+07
45,2022-05-20T00:00:00+00:00,1653004800000.0,0.4511,0.4588,0.4191,0.4325,2.358605305730000e+07
46,2022-05-21T00:00:00+00:00,1653091200000.0,0.4325,0.4431,0.4206,0.4344,2.331693802100000e+07
47,2022-05-22T00:00:00+00:00,1653177600000.0,0.4344,0.4489,0.4230,0.4420,2.201282781480000e+07
48,2022-05-23T00:00:00+00:00,1653264000000.0,0.4420,0.4522,0.4096,0.4165,2.259577373480000e+07

In [4]:

#df.index.name='Index1' = to give index a name 
#/markets/GMT-PERP/candles?resolution={resolution}&start_time={start_time}&end_time={end_time}
market_hr = requests.get('https://ftx.com/api/markets/GMT-PERP/candles?resolution=3600&start_time=1649116800&end_time=1653264000').json()
df_hr = pd.DataFrame(market_hr['result'])
df_hr

NameError: name 'df_hr' is not defined

In [ ]:
s = pd.date_range('2022-04-05', '2022-05-23', freq='D').to_series()
s.dt.dayofweek
weekDay = s.dt.dayofweek.tolist()
print(weekDay)

In [ ]:
h = pd.date_range('2022-04-05', '2022-05-23', freq='h').to_series()
h.dt.hour

hour_day = h.dt.hour.tolist()
print(hour_day)

In [ ]:
df_hr['hour_day'] = pd.to_datetime(df_hr['startTime']).dt.hour
print(df_hr.hourOfDay)

In [ ]:
df_monday_grouped = df_monday.groupby('hour').count()

In [5]:
# code code 

"""
1. Create a list of week of day 
2. Create a list of hours of the day 
3. make a dataframe of 2 columns one is a day in the week and the second is hours in that day 
4. Make a new dataframe where one column is monday and the second is hours for that day 
"""

#1. Create a list of week of day 
week_days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

#2. Create a list of hours of the day 
hours = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]

#3. make a dataframe of 2 columns one is a day in the week and the second is hours in that day 
df_week_hours = pd.DataFrame(columns=['week_day', 'hour'])
df_week_hours['week_day'] = week_days
df_week_hours['hour'] = hours

#4. Make a new dataframe where one column is monday and the second is hours for that day 
df_monday = df_week_hours[df_week_hours['week_day'] == 'Monday']
df_monday.head()

#5. Make a new dataframe where one column is tuesday and the second is hours for that day 
#df_tuesday = df_week_hours[df_week_hours['week_day'] == 'Tuesday']
#df_tuesday.

ValueError: Length of values (24) does not match length of index (7)